/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Calculator {
    public double calculate(double num1, double num2, char operation) {
        double result;

        /* TODO
         * Implement the calculate method to perform basic arithmetic operations
         * (+, -, *, /)
         * Make sure to handle the case where division by zero is attempted
         * Feel free to reach out to Thien or Otto if you have any questions.
         * You can also look in the test file to see how the method is expected to behave.
         */
        return result;
    }
}
